export const CONFIG = {
  API_BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:4000',
  S3_BUCKET_URL: import.meta.env.VITE_S3_BUCKET_URL || '',
  STRIPE_PUBLISHABLE_KEY: import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY || '',
  COGNITO_USER_POOL_ID: import.meta.env.VITE_COGNITO_USER_POOL_ID || '',
  COGNITO_CLIENT_ID: import.meta.env.VITE_COGNITO_CLIENT_ID || '',
  APP_NAME: 'Matrimony',
  APP_TAGLINE: 'Where Tamil Hearts Find Home',
  SUPPORT_EMAIL: 'support@matrimony.com',
  MAX_PHOTOS: 6,
  MAX_PHOTO_SIZE_MB: 5,
  OTP_LENGTH: 6,
  OTP_RESEND_COOLDOWN_SECONDS: 60,
  CHAT_POLL_INTERVAL_MS: 5000,
  ITEMS_PER_PAGE: 20,
} as const;
